//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGOGamble
{
    using System;
    using System.Collections.Generic;
    
    public partial class bets
    {
        public int ID { get; set; }
        public double amount { get; set; }
        public int roundID { get; set; }
        public int userID { get; set; }
    }
}
