//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGOGamble
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int ID { get; set; }
        public string message { get; set; }
        public int userID { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual users users { get; set; }
    }
}
