//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGOGamble
{
    using System;
    using System.Collections.Generic;
    
    public partial class roundkey
    {
        public int ID { get; set; }
        public System.DateTime date { get; set; }
        public string @public { get; set; }
        public string secret { get; set; }
        public ICollection<round> round { get; set; }
    }
}
