//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGOGamble
{
    using System;
    using System.Collections.Generic;
    
    public partial class rounds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rounds()
        {
            this.bets = new HashSet<bets>();
        }
    
        public int ID { get; set; }
        public int number { get; set; }
        public Nullable<int> outcome { get; set; }
        public System.DateTime runtime { get; set; }
        public int keyID { get; set; }
        public sbyte complete { get; set; }
    
        public virtual roundkeys RoundKey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bets> bets { get; set; }
    }
}
