//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGOGamble
{
    using System;
    using System.Collections.Generic;
    
    public partial class round
    {
        public int ID { get; set; }
        public int number { get; set; }
        public int outcome { get; set; }
        public System.DateTime runtime { get; set; }
        public int keyid { get; set; }
        public sbyte complete { get; set; }
    }
}
